package executor

import (
	"context"
	"errors"
	"os/exec"
	"strings"
)

//todo:generated by ai

// Exec runs command from within workDir and returns the combined stdout+stderr
// produced by the process. The context may be used to cancel / time out the
// running command.
//
// Execution model (direct command execution):
//   - The command is split into an executable plus explicit arguments and that
//     executable is launched directly with exec.CommandContext — no interactive
//     shell is wrapped around it.
//   - The one exception is a batch file (.bat/.cmd) on Windows: Windows cannot
//     execute a batch file as a direct executable, so such commands are routed
//     through "cmd.exe /c". This is required for the bat executor to function.
//
// workDir is set as the process working directory. When it is empty the
// process inherits the caller's working directory.
func Exec(ctx context.Context, command, runner, workDir string) ([]byte, error) {
	args, err := SplitCommand(command)
	if err != nil {
		return nil, err
	}
	if len(args) == 0 {
		return nil, errors.New("empty command")
	}

	var exe string
	var params []string

	if runner != "" {
		exe = runner
		params = args[0:]
	} else {
		exe = args[0]
		params = args[1:]
	}

	cmd := exec.CommandContext(ctx, exe, params...)

	if workDir != "" {
		cmd.Dir = workDir
	}

	output, err := cmd.CombinedOutput()
	if err != nil {
		// err is a *exec.ExitError when the process exited non-zero.
		return output, err
	}
	return output, nil
}

// SplitCommand splits a command line into an executable and its arguments,
// honouring double quotes so that paths and arguments containing spaces remain
// a single token.
func SplitCommand(command string) ([]string, error) {
	var tokens []string
	var current strings.Builder
	inQuotes := false

	for _, r := range command {
		switch {
		case r == '"':
			inQuotes = !inQuotes
		case (r == ' ' || r == '\t') && !inQuotes:
			if current.Len() > 0 {
				tokens = append(tokens, current.String())
				current.Reset()
			}
		default:
			current.WriteRune(r)
		}
	}

	if inQuotes {
		return nil, errors.New("unbalanced quotes in command")
	}
	if current.Len() > 0 {
		tokens = append(tokens, current.String())
	}
	return tokens, nil
}
